### PR TITLE
Fix exported TS types

### LINKED ISSUE #598: When trying to build an angular project in prod it cannot build due to missing classes
**Do you want to request a *feature* or report a *bug*?**
Report a bug:

**What is the current behavior?**
When trying to use ng build --prod with Pusher-js npm installed I get 3 errors all Authentication related. Tried to import them into 
App.module.ts
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**
That the ng-build --prod will exectute succesfully 
**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Latest version of pusher, not too sure if this worked on previous versions. 
image_2022-05-24_184453828
image
image

### PR DESCRIPTION
**Pull request by MeenaAlfons**
## What does this PR do?

- Fix exported TS types in index.d.ts by removing deleted types and addinng new types.
- Regenerating `types` directory from scratch. That results in removing deleted files.

Fixes #598

## Checklist

- [x] All new functionality has tests.
- [x] All tests are passing.
- [x] New or changed API methods have been documented.
- [x] `npm run format` has been run

### CODE REVIEW

**Review by agatav — APPROVED** [review]

**Review by sonologico — APPROVED** [review]

File: index.d.ts [hunk 1]
```diff
@@ -1,8 +1,13 @@
 export {
-  Authorizer,
+  DeprecatedAuthOptions,
+  ChannelAuthorizerGenerator,
+} from './types/src/core/auth/deprecated_channel_authorizer';
+export {
   AuthOptions,
-  AuthorizerGenerator,
```
Comment (stof) [inline index.d.ts:4]: Removing AuthorizerGenerator breaks https://github.com/dirkbonhomme/pusher-js-auth. Was this really removed in a minor version rather than in a major version ? Or is this just a mistake in the type declarations ?

Comment (stof) [reply index.d.ts:4]: Looking at the diff, it seems like this was renamed to `ChannelAuthorizerGenerator`. But this is a BC break (as it effectively removes the old type and adds a new one).

Comment (MeenaAlfons) [reply index.d.ts:4]: That's definitely a mistake. We'll fix it ASAP. Thanks for reporting it. 🙏

Comment (MeenaAlfons) [reply index.d.ts:4]: Fixed in https://github.com/pusher/pusher-js/pull/615
